export enum ConfigurationsEnum {
  HOST = 'HOST',
  PORT = 'PORT',

  JWT_SECRET = 'JWT_SECRET',

  DB_HOST = 'DB_HOST',
  DB_PORT = 'DB_PORT',
  DB_USERNAME = 'DB_USERNAME',
  DB_PASSWORD = 'DB_PASSWORD',
  DB_NAME = 'DB_NAME',

  APP_URL = 'APP_URL',
  JWT_EXPIRE_IN = 'JWT_EXPIRE_IN',

  FIREBASE_PROJECT_ID = 'FIREBASE_PROJECT_ID',
  FIREBASE_PRIVATE_KEY = 'FIREBASE_PRIVATE_KEY',
  FIREBASE_CLIENT_EMAIL = 'FIREBASE_CLIENT_EMAIL',
}
